# Generated by Django 5.2.8 on 2025-11-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_materialrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='workreport',
            name='time_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
