# Generated by Django 5.2.8 on 2025-11-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_workreport_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='workreport',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_progress', max_length=30),
        ),
    ]
