# Generated by Django 5.2.8 on 2025-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_workreport_time_spent_workreport_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='material_photos/'),
        ),
    ]
