# Generated by Django 5.2.8 on 2025-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_materialrequest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
