# Generated by Django 5.2.8 on 2025-11-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_site_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
