# Generated by Django 5.2.8 on 2025-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_materialrequest_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
